### ISSUE TITLE
CI broken due to missing libXss.so

### ISSUE THREAD

**Issue by AmirrezaNasiri** [edbizarro/gitlab-ci-pipeline-php#102]
Hi

Sounds like our CI is broken from yesterday because of missing `libXss.so` for chromium to run. Also, isn't it better to lock the chromium version to a stable one explicitly?

```
(node:36) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/builds/project/cms/node_modules/penthouse/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
    at onClose (/builds/project/cms/node_modules/penthouse/node_modules/puppeteer/lib/Launcher.js:750:14)
    at Interface.<anonymous> (/builds/project/cms/node_modules/penthouse/node_modules/puppeteer/lib/Launcher.js:739:50)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:416:8)
    at Socket.onend (readline.js:194:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:36) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by edbizarro** [comment]
hi @AmirrezaNasiri that's a good idea, I'll make some changes to proper lock the version

**Comment by goraxan** [comment]
I solved this error by installing the missing dependencies, as explained in https://medium.com/@ssmak/how-to-fix-puppetteer-error-while-loading-shared-libraries-libx11-xcb-so-1-c1918b75acc3

@edbizarro it'd be nice if you added that in the Dockerfile
